### ISSUE TITLE
list_queue needs lowest priority (applies after all other filter)

### ISSUE THREAD

**Issue by lostsubstance** [Flexget/Flexget#1092]
per discussion: http://discuss.flexget.com/t/movie-queue-migration-question/2248

**Comment by gazpachoking** [comment]
We were discussing this in irc as well. It should do the removing from the list on the learn phase I think, rather than the filter phase, to ensure output went fine. We need to add some logic on filter phase then to make sure not to accept more than one entry based on the same queue item somehow though.
