### ISSUE TITLE
`seen add` crashes

### ISSUE THREAD

**Issue by grr** [Flexget/Flexget#1463]
$ flexget seen add http://imdb.com/title/tt3691740/
    Traceback (most recent call last):
    File "/tmp/bin/flexget", line 9, in <module>
        load_entry_point('FlexGet', 'console_scripts', 'flexget')()
    File "/tmp/flexget/flexget/__init__.py", line 42, in main
        manager.start()
    File "/tmp/flexget/flexget/manager.py", line 326, in start
        self.handle_cli()
    File "/tmp/flexget/flexget/manager.py", line 353, in handle_cli
        options.cli_command_callback(self, command_options)
    File "/tmp/flexget/flexget/plugins/cli/seen.py", line 16, in do_cli
        seen_add(options)
    File "/tmp/flexget/flexget/plugins/cli/seen.py", line 39, in seen_add
        seen.add(seen_name, 'cli_add', {'cli_add': seen_name})
    AttributeError: 'module' object has no attribute 'add'

- Flexget Version: 2.5.1
- Python Version: 2.7.11
- Installation method: git
- OS and version: OS X

**Comment by liiight** [comment]
crap, my bad, removed that in the api refactor. I'll re add, though I feel adding directly to seen is kind of a hack. why not inject to task with learn flag instead?

**Comment by grr** [comment]
inject syntax is not as simple to use and people have been using `seen add` for literally years. software should be backwards-compatible when possible, not forcing users to unnecessarily change their learned habits.

**Comment by liiight** [comment]
i agree with what you said and ill re-add what i removed because it was removed by accident.
That being said, just that something has existed for a long period of time does not make it un-susceptible to change. I'll get a discussion going about this with the other team members and if and when this behaviour will be changed, it will be done in the proper upgrade manner.
