### ISSUE TITLE
`series list all` doesn't take seen into account

### ISSUE THREAD

**Issue by afranke** [Flexget/Flexget#1528]
One episode was making an error for flexget this morning, so I downloaded it manually and marked it as seen. I then use `series list all` which still tells me I'm 1 episode behind.

I expect that `series list all` tells me I'm up to date even if it was not responsible for the download.

Maybe the call to get_latest_release in function display_summary in plugins/cli/series.py should pass downloaded=False ?

- Flexget Version: 2.7.0
- Python Version: 3.5.2
- Installation method: pip in a virtualenv

**Comment by cvium** [comment]
An episode being marked as `seen` does not and should not have any impact on series advancement. If you want Flexget to 'learn' of your manual download, take a look at the CLI arguments `--inject`, `--learn`.

**Comment by gazpachoking** [comment]
You can also use the `flexget series begin` command to advance the series plugin to a given episode manually. That's probably the easiest way.

**Comment by afranke** [comment]
What's the point of `seen add` then?

**Comment by gazpachoking** [comment]
Two different plugins. The seen plugin rejects specific entries that were accepted before, but has no knowledge about information like series episode number, just the exact title and url of the entry. It works on all tasks, regardless of whether they are series or movie or otherwise. The series plugin works with a lot more parsed metadata, not just the exact name of entries. There is a bit of overlap in the functionality, but you want to be using the series plugin directly when telling flexget about new episodes you added outside flexget.

**Comment by afranke** [comment]
Ok, thanks.
