### ISSUE TITLE
Adding new column to `plugins` output

### ISSUE THREAD

**Issue by haarts** [Flexget/Flexget#1666]
I'm trying to understand the concepts of 'phase' and 'interface' of a plugin. The output of the CLI command `flexget plugins` has been helpful. But I think I noticed that the output is missing a column. It has 'Keyword', 'Phases' and 'Flags', but no 'Interfaces'. I found out that all plugins _do_ defined a list of interfaces for themselves. 

Shall I create a PR adding the column 'Interfaces' to the output?
I wanted to ask before I put the effort in.

And if someone can explain what a 'phase' and 'interface' is I'll write up a wiki page. ;)

**Comment by gazpachoking** [comment]
Seems like a good idea to me.

Interface is a sort of new concept to describe what roll a plugin can fill, now that we have more than one. The 'task' interface is the main one, which are all the plugins that can be configured directly inside a task. Other notable interfaces are 'list', which can be configured inside of one of the list controlling plugins (list_add, list_match, list_remove, etc.), 'notifiers' which are configured inside 'notify' plugin.

Phases are mostly meant to be internal, so that the user _shouldn't_ (in most common cases) need to  worry about what order plugins in a task run. A task is run by executing a sequence of phases in order (input, filter, output) being the main 3. The 'task' interface plugins can hook any one (or more) of these phases to make sure they run in a certain order within the task. (e.g. all plugins hooking the input phase need to run to generate the entries before a plugin hooking the filter phase can decide whether the entries are wanted or not.)
