### ISSUE TITLE
Errors with new smtp connections

### ISSUE THREAD

**Issue by calisro** [Flexget/Flexget#1761]
I'm seeing some issues with the fix put in for smtp connections 

https://github.com/Flexget/Flexget/issues/1751

```
2017-03-28 08:20 ERROR    notify_entry  Email-SummaryTV please run connect() first
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/notify.py", line 103, in send_notification
    send_notification(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/notification_framework.py", line 117, in send_notification
    notifier.notify(title, message, rendered_config)  # TODO: Update notifiers for new api
  File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/email.py", line 165, in notify
    self.mail_server.sendmail(email['From'], config['to'], email.as_string())
  File "/usr/lib/python2.7/smtplib.py", line 733, in sendmail
    (code, resp) = self.mail(from_addr, esmtp_opts)
  File "/usr/lib/python2.7/smtplib.py", line 480, in mail
    self.putcmd("mail", "FROM:%s%s" % (quoteaddr(sender), optionlist))
  File "/usr/lib/python2.7/smtplib.py", line 341, in putcmd
    self.send(str)
  File "/usr/lib/python2.7/smtplib.py", line 333, in send
    raise SMTPServerDisconnected('please run connect() first')
SMTPServerDisconnected: please run connect() first

```

**Comment by liiight** [comment]
Please paste debug logs

**Comment by liiight** [comment]
Nm, I know what I did wrong... Will fix and test ASAP

**Comment by calisro** [comment]
okay. np. Thanks.  I hv debug enabled for now anyway.

**Comment by ivanich** [comment]
Мар 28 18:14:56 ubuntu-homeserver flexget[2283]: 2017-03-28 18:14 INFO     transmission  lostfilm        "(The Walking Dead). ,    (S07E15) [1080p]" torrent added to transmisМар 28 18:15:03 ubuntu-homeserver flexget[2283]: 2017-03-28 18:15 ERROR    notify_entry  lostfilm        u'smtp_username'
Мар 28 18:15:03 ubuntu-homeserver flexget[2283]: Traceback (most recent call last):
Мар 28 18:15:03 ubuntu-homeserver flexget[2283]:   File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/notify.py", line 103, in send_notification          Мар 28 18:15:03 ubuntu-homeserver flexget[2283]:     send_notification(*args, **kwargs)                                                                                       Мар 28 18:15:03 ubuntu-homeserver flexget[2283]:   File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/notification_framework.py", line 117, in send_notifiМар 28 18:15:03 ubuntu-homeserver flexget[2283]:     notifier.notify(title, message, rendered_config)  # TODO: Update notifiers for new api
Мар 28 18:15:03 ubuntu-homeserver flexget[2283]:   File "/usr/local/lib/python2.7/dist-packages/flexget/plugins/notifiers/email.py", line 161, in notify
Мар 28 18:15:03 ubuntu-homeserver flexget[2283]:     self.username = config['smtp_username']
Мар 28 18:15:03 ubuntu-homeserver flexget[2283]: KeyError: u'smtp_username'

I never had smtp_username and password in my config because smtp server in my local network and it didn't require auth
