### ISSUE TITLE
Where is database data located ?

### ISSUE THREAD

**Issue by breneser** [Flexget/Flexget#2240]
Hi, this is not really an issue, but rather a question I couldn't find the answer to.

When I run flexget in a docker container it creates a db-config.sqlite file next to config.yml file. Is that the database? Is it possible to change the location of database so that I can put it in a volume for data?

**Comment by gazpachoking** [comment]
The database gets placed in the same folder as the config file, as you noticed. You could try moving it and creating a symlink in its place pointing to your actual database file. Also, [the forum](http://discuss.flexget.com) is a good place for these kinds of questions rather than in the bug tracker.
