### ISSUE TITLE
flexget should publish and official container

### ISSUE THREAD

**Issue by ssbarnea** [Flexget/Flexget#2359]
While there is [some documentation on how to manually build a container with docker](https://flexget.com/InstallWizard/SynologyNAS/Docker), there is no official flexget container published. 

A search on https://hub.docker.com/search?q=flexget&type=image shows that are more than 180 different flexget containers published by individuals, but none of them is actively maintained.

Publishing a container could assure that the code runs with exactly the correct versions of all dependencies and can ease the support burden on flexget.

I would be glad to help on that aspect and I would see the benefits of having others doing the same instead of having every doing DIY from zero and having to deal with the same issues again and again.

**Comment by frankyw** [comment]
This would be a great enhancement, would love to see this.

**Comment by paulpoco** [comment]
https://github.com/paulpoco/arch-delugevpn/tree/dev

You welcome to fork my Github of Deluge/OpenVPN/Privproxy/Flexget?

docker pull paulpoco/arch-delugevpn-dev:Dev

**Comment by paulpoco** [comment]
> While there is [some documentation on how to manually build a container with docker](https://flexget.com/InstallWizard/SynologyNAS/Docker), there is no official flexget container published.
> 
> A search on https://hub.docker.com/search?q=flexget&type=image shows that are more than 180 different flexget containers published by individuals, but none of them is actively maintained.
> 
> Publishing a container could assure that the code runs with exactly the correct versions of all dependencies and can ease the support burden on flexget.
> 
> I would be glad to help on that aspect and I would see the benefits of having others doing the same instead of having every doing DIY from zero and having to deal with the same issues again and again.

A Lot of the time once you install the Docker container, at least myself I update from within the container.  I know it is bad but my Published Docker is updated about once per year.  If it works why mess with it.

**Comment by ksurl** [comment]
the issue is not everyone uses all the plugins so some dependencies aren't installed or needed. unless you go with the model to install everything. some of us use external tools that integrate with flexget as well that are called in tasks. you could go with a base container with basics and somehow make it customizable based on environment variables or something else to include pip modules, apt packages (or non debian based containers, other package managers). 

there's also the work of setting up auto builds on new releases and making sure it passes compatibility tests with dependencies.

**Comment by Winter** [comment]
> the issue is not everyone uses all the plugins so some dependencies aren't installed or needed. unless you go with the model to install everything. some of us use external tools that integrate with flexget as well that are called in tasks. you could go with a base container with basics and somehow make it customizable based on environment variables or something else to include pip modules, apt packages (or non debian based containers, other package managers).
> 
> there's also the work of setting up auto builds on new releases and making sure it passes compatibility tests with dependencies.

The issue of requiring all dependencies is not really that big of a deal. There’s not many packages and an alpine container ends up between 150-250mb (before cleaning up) 

Clarifying on external tools; do you mean those that are exposed by web services or something that requires and executable?

Adding optional apk/apt/pip packages is easy enough.

And finally, the auto building. Docker makes it extremely simple to setup basic versioning and auto builds based off a branch on github, I’d highly suggest you check it out on a private repo. Given that flexget already has checks in place for the source code, only basic checks to ensure the docker container successfully builds and runs is required. 

As I said, I’m more than happy to help setup an official docker image. I have my own dockerfile that I quickly threw together in a couple of minutes but can be easily modified to make it a little more proper.

**Comment by ksurl** [comment]
if we have an official image, most of these could be worked out with a consensus, but that's just my experience as well looking at all the different images already on docker hub. everyone adds only what they need and if you're lucky, they have a public Dockerfile or linked to github so you can modify for your own use. 

as for external tools, yes I'm talking about calling executables with `exec`. I also include netcat in my image for troubleshooting network issues when connecting to other services in my network

one other question is if we would want a new image on every release, or go with the plex model where it updates to latest on startup. one solution would be to provide a variable to enforce a specific version or just go with latest. the only issue is if a new release requires a newer version of a dependency. then it's better off doing a new build every release

**Comment by Winter** [comment]
Given that Flexget is designed for power users, I definitely do think we should have an environment variable to add packages. Removes the complexity of users requiring to fork and build the Dockerfile.  


A mockup docker-compose would go along the lines of the following..
```yaml
version: "2"
services:
    flexget:
        image: flexget/flexget
        container_name: flexget
        environment:
        - PUID= ...
        - PGID= ...
        - TZ= ...
        - WEBUI_PASSWORD= ...
        - PACKAGES= "netcat-openbsd ..."
        volumes:
        - ... :/config
        ports:
        - 5050:5050
        restart: unless-stopped
```
Although this does raise the question of who has control of the [flexget organization](https://hub.docker.com/u/flexget) on docker hub.

As for the question of whether we should go with the plex model of things, I think a new build on every release would be the best option, as it gives a versioned history on docker so it's easy to pull a specific version.

**Comment by ksurl** [comment]
We could start by dropping a message in slack/discord/irc where the devs are most active.

**Comment by Winter** [comment]
> 
> 
> We could start by dropping a message in slack/discord/irc where the devs are most active.

I did put a link to here in the discord, but no one seems to be interested in the topic apparently.

**Comment by ksurl** [comment]
unfortunately, not much we can do until we can find someone who has access to the flexget org account on docker hub. unless we get the devs blessing to use a different account and put that link on the wiki

**Comment by frankyw** [comment]
I can recommend https://github.com/wiserain/docker-flexget, updated continuously with latest flexget, has a decent amount of plugins by default and support for custom plugins, plus support for setting UID/PID. I have been using it for over a year and it works perfectly.

**Comment by ksurl** [comment]
I've tried it before but did not realize it supported custom packages via startup script. it is one of if not the most popular one by pulls

**Comment by kristenmills** [comment]
I think this is a good idea. I've got ownership on the flexget dockerhub org (as does @liiight @gazpachoking and @stevezau) so if someone wants to start a PR for this, I'm good with publishing an official flexget docker image.

**Comment by ksurl** [comment]
## Current Dockerfile:

I'm looking at the existing Dockerfile in the repo. It was last updated 6 months ago though I'm not sure of the use since it is not being built on Docker hub. could it be currently only used for private local builds by some users? 

It is using a multistage build to cache pip wheels before doing the install in the 2nd stage.
The commit notes say it cuts down an 800 mb image to 300mb but that is still quite huge for an alpine image (my python based image which is debian/ubuntu based is clocking in at 212 and my alpine image is under 50mb with more dependencies installed). If we're automating builds, I don't think it matters as much on saving build time. it takes a couple minutes max in my experience.

also running as root

I don't want to break anyone's workflow which depend on the current Dockerfile. should we setup a separate repo for this? or any other more elegant solutions?

## Suggested main priorities:

* python:alpine based image to avoid installing python and pip manually (could be more granular and specify python:3-alpine though alpine should default to 3?)
* custom dependencies install at startup for pip packages not included by default
* custom UID/GID via environment variable like linuxserver images to avoid running as root
* avoid opinionated dependencies and let people fork if they want something more custom (or build their own from scratch)

**Comment by ksurl** [comment]
PR for a new docker hub build branch from @Winter should be incoming shortly. We worked out the details for a 1.0 Dockerfile and startup script

**Comment by Winter** [comment]
As there is an existing Dockerfile in the root of the directory, I don't want to mess up any of the work-flows. So I've made a separate repo for it and it's here https://github.com/Winter/docker-flexget, if @kristenmills wants me to open a PR I can, but I'll probably do it under a separate folder (like /docker).

**Comment by liiight** [comment]
@Winter I think a PR would be best. I looked at the Dockerfile you created and there's a few changes I think we need to discuss for the "official" version. In fact, why don't I just start the discussion here:

- The entry point should be the "official" flexget entry point. Either install the package locally via `pip install . -e` or just call `python flexget_vanilla.py`
- If I'm reading the file correctly, you installed all the 3rd party deps by default. I'm not sure that is the best use case by default. Maybe we should create several installation tags? Something like `lite` & `full`?
- Same question with the web-server. The image can be installed as an always-up service, or a one time runner. I wonder what's the best way to configure that as well.
- I definitely think we need to enable passing a `config.yml` from outside.
- We need to make sure CLI commands are running as expected when the service is up via it's daemon.

That's some stuff off the top of my head. I apologize if some of these are already present or if I am interpreting stuff incorrectly. My experience with Docker is limited.

Thank you very much for taking the initiative on this!

**Comment by Winter** [comment]
@liiight I'll put together a PR now, but I'll take the opportunity to answer your questions in order! 

1. Easy enough, probably best to call `python flexget_vanilla.py` if that's what is desired.
2. I disagree with creating two separate tags. With all required dependencies installed, it is [58.29MB](https://hub.docker.com/repository/docker/winterau/flexget/tags?page=1) and uncompressed it is only [186MB](https://i.imgur.com/6CAiPQM.png). It feels a bit redundant to have a lite tag given these sizes, and especially since we would want the latest tag pointed at the full version. 
3. Could you clarify what you mean? If you mean that you want an option to just execute all tasks and exit that's easy enough. 
4. If by "passing a `config.yml` from outside" you're referring to the _sample_ `config.yml` then there's no issue here. /config is mounted to the outside of the docker container and is intended for users to edit to their whim. 
5. Could you also clarify this also? If you mean running `# docker exec -it Flexget sh` and running for example `flexget execute` and it being passed through to the daemon then that is working fine. 

Feel free to mention me, @Winter in the chat sometime and I'll be happy to have a chat.

**Comment by ksurl** [comment]
for the webserver, it is dependent on the user's config if it's enabled. the included config is just a failsafe if the container is started without a config folder mounted so it starts cleanly with a default config.

for running adhoc cli commands, you would run on the host `docker exec -it -u $UID:$GID $CONTAINER_NAME flexget execute blah blah`

I have an alias set for flexget='docker exec -it -u $UID:$GID $CONTAINER_NAME flexget' in my .bashrc file. the only downside is the relatively new cli color output feature doesn't work since the internal shell is sh (either that, or it doesn't make it out of the docker exec wrapper).
