### ISSUE TITLE
Telegram Notification No Rendering

### ISSUE THREAD

**Issue by soloam** [Flexget/Flexget#2552]
Hello I have a task that sends notifications to telegram

   ```
 notify:
      task:
        via:
          - email:
              html: yes
              from: '{? email.from ?}'
              to: 
                - '{? email.to1 ?}'
              smtp_host: smtp.gmail.com
              smtp_port: 587
              smtp_username: '{? email.from ?}'
              smtp_password: '{? email.pass ?}'
              smtp_tls: yes
      entries:
        what: accepted
        title: |+
         {% if series_name is defined -%}
           {{series_name}} {{series_id}} was moved to server
         {% elif imdb_name is defined -%}
           {{imdb_name}} ({{imdb_year}}) was moved to server
         {% else -%}
           {{ title }} was moved to server
         {%- endif -%}
        message: |+
          {% if series_name is defined -%}
          * <<Novo Episódio>> *
          {{series_name}} - {{series_id}}
          {{tvmaze_episode_name|d(tvdb_ep_name)|d('')}}
          
          [Imágem]({{tvmaze_series_original_image|replace("_", "%5F")}})
          [Mais Imformações]({{tvmaze_series_url|replace("_", "%5F")}})
          {% elif imdb_name is defined -%}
           * <<Novo Filme>> *
          {{imdb_name}} ({{imdb_year}})
          {{imdb_score}}/10 - {{imdb_votes}} votos
          
          {{imdb_genres|join(', ')|title}} 
          *Plot:* {{imdb_plot_outline}}
          [Imágem]({{tmdb_posters[0]|replace("_", "%5F")}})
          [Mais Imformações]({{imdb_url|d('')}})
          {% else -%}
          {{title}}
          {%- endif -%}
        via:
          - pushbullet:
              api_key: '{? pushbullet.key ?}'
              url: '{{ imdb_url }}'
          - telegram:
              bot_token: '{? telegram.token ?}'
              parse_mode: markdown
              recipients:
                - group: '{? telegram.group ?}'
```

This works on sending the notifications, but sometimes, and with no apparent reason, sometimes I receive in telegram (pushbullet also) the jinja code as string, the strange is that if I reprocess the output, the output is rendered, and sometime I need more that one try to have it render:

```
{% if seriesname is defined -%}
* <<Novo Episódio>> *
{{seriesname}} - {{seriesid}}
{{tvmazeepisodename|d(tvdbepname)|d('')}}

[Imágem]({{tvmazeseriesoriginalimage|replace("", "%5F")}})
[Mais Imformações]({{tvmazeseriesurl|replace("", "%5F")}})
{% elif imdbname is defined -%}
 * <<Novo Filme>> *
{{imdbname}} ({{imdbyear}})
{{imdbscore}}/10 - {{imdbvotes}} votos

{{imdbgenres|join(', ')|title}} 
Plot: {{imdbplotoutline}}
Imágem}})
Mais Imformações}})
{% else -%}
{{title}}
{%- endif -%}
```

I can't find a pattern on this, it looks a bit random. Anyone with a similar problem?

Thank You

**Comment by liiight** [comment]
I think this is because of tmdb_posters[0]. In case there's no TMDB posters for this object this will silently fail on this (which is not good). As a workaround  you can check TMDB posters if it's not empty by checking `{{ if tmdb_posters }}`

**Comment by soloam** [comment]
And that would not make it fail always? If I try to process again it will work, sometimes at first try, sometimes it needs more that on try! This makes it very hard to me to discover the problem, because the error is not constant! Sometimes when I reproduce the scenario to try to debug the error, it just works, no changes made!

**Comment by liiight** [comment]
like i said, i think varies on the data itself. Did you check the logs when there are failures? I imagine something should be present there.

**Comment by BrutuZ** [comment]
I worked around that issue a couple times in my config since I use MANY fields (its based off the same template you got yours from, but I expanded it), so just to add an alternative since enclosing in Jinja `{% if %}{% endif %}` can get a little cumbersome if you have to use several of them:
```diff
- [Imágem]({{tmdb_posters[0]|replace("_", "%5F")}})
+ [Imágem]({{(tmdb_posters|d|first)|d(imdb_photo)|d|replace("_", "%5F")}})
```
Explanation: 
- `(tmdb_posters|d|first)` - Return `tmdb_posters` if defined, or an empty but valid value. Picks the first value on `tmdb_poster` if defined. Effectively the same as `{% if tmdb_posters %}{{tmdb_posters[0]}}{% endif %}`
- `d(imdb_photo)` - If the previous returns an empty value, fallback to the IMDB poster (assuming you're already using `imdb_lookup` since other IMDB fields are being used and again, I use the same template :P )
- The last `|d` is to once again just return and empty but valid string in case neither of the lookups return a value

> Did you check the logs when there are failures?

**IIRC**, logs only tell something along the lines of "Failed to render message" and at the end of stack trace just "NoneType is not an iteratable" but not what field triggered it.
At least not in the old logs that is, with `|d` fallbacks all over the place now I haven't had this happen since the migration to loguru, which might make this debug easier with its variable value display.

**Comment by soloam** [comment]
That seemed to solve the problem!

Thank you
