### ISSUE TITLE
[Improvement] Don't output "WARNING: Task didn't produce any entries." when using rss with "all_entries: no".

### ISSUE THREAD

**Issue by gituck** [Flexget/Flexget#2807]
As per definition "all_entries: no" does only output changes:

"If you would like to improve the performance of a task using this plugin, you can set all_entries: no to have each entry only created on the first run it is seen."

Flexget throws a warning that the task didn't output anything:

"Task didn't produce any entries. This is likely due to a mis-configured or non-functional input."

But this is the expected behaviour. (When nothing new was added to the RSS Feed.)

**Comment by ksurl** [comment]
do you only get this when running cli manually? I don't get this message with default log level info when running as scheduled task in daemon mode

**Comment by gituck** [comment]
Hm, I didn't consider this but I've started the daemon and scheduled the task. No additional verbosity.Just to be sure is there a way to get the current log level? (daemon ist running in background)

**Comment by ksurl** [comment]
It defaults to info if not set.

**Comment by gituck** [comment]
I've just checked it to be sure, started it like this:

"flexget daemon start -d"

**Comment by soloam** [comment]
You could use [no_entries_ok](https://flexget.com/Plugins/no_entries_ok) to avoid this messages

**Comment by gazpachoking** [comment]
This warning is supposed to be suppressed already if the `all_entries: no` actually does anything. The two cases that would happen is if the [server returns a 304](https://github.com/Flexget/Flexget/blob/c0f9a70cf2ad9a93b53a52d80df70b8476f7a456/flexget/plugins/input/rss.py#L288), (feed hasn't changed since last request,) or if the server doesn't support that, when [remembering the last processed item](https://github.com/Flexget/Flexget/blob/c0f9a70cf2ad9a93b53a52d80df70b8476f7a456/flexget/plugins/input/rss.py#L432). If the feed might be empty anyway, `no_entries_ok` plugin should be used, and would be needed no matter whether `all_entries: no` was used or not. If there are some edge cases not being taken into account, please reopen this with more info.
