### ISSUE TITLE
Series plugin unable to parse episode sequence numbers over 3 digits in length

### ISSUE THREAD

**Issue by Wilkolicious** [Flexget/Flexget#3250]
### Expected behaviour:
Flexget series plugin should be able to parse an episode number with over 3 digits in length

### Actual behaviour:
The following error occurs and the episode is not recognised as being a part of the series:
> 2021-11-23 00:04:51 INFO     parser_internal nyaa.si - judas Title `[Judas] One Piece - 1000 [1080p][HEVC x265 10bit][Multi-Subs] (Weekly)` looks like series `One Piece` but cannot find any series numbering.

### Steps to reproduce:
- Have config which references a series entry that has over 999 episodes from RSS
- Run flexget (I personally run in daemon mode, but probably not relevant)
- Episode not recognised

#### Config:
[flexget_config.txt](https://github.com/Flexget/Flexget/files/7585172/flexget_config.txt)

#### Log:
<details>
 <summary>(click to expand)</summary>

```
2021-11-23 00:04:51 INFO     parser_internal nyaa.si - judas Title `[Judas] One Piece - 1000 [1080p][HEVC x265 10bit][Multi-Subs] (Weekly)` looks like series `One Piece` but cannot find any series numbering.
```
Let me know if you want the entire log.  None of the log seems interesting.
</details>

### Additional information:

- FlexGet version:
```
3.1.153
You are on the latest release.
```
- Python version: `Python 2.7.18`
- Installation method:  Of flexget?  Via `pip`
- Using daemon (yes/no): Yes
- OS and version:
```
Linux wilko-server 5.4.0-89-generic #100-Ubuntu SMP Fri Sep 24 14:50:10 UTC 2021 x86_64 x86_64 x86_64 GNU/Linux
```
```
No LSB modules are available.
Distributor ID: Ubuntu
Description:    Ubuntu 20.04.3 LTS
Release:        20.04
Codename:       focal
```
- Link to crash log: N/A

Is the problem line here: 
https://github.com/Flexget/Flexget/blob/develop/flexget/components/series/next_series_episodes.py#L46

**Comment by astrotee** [comment]
I think I've found the problem:
https://github.com/Flexget/Flexget/blob/97ca6d2219c43f723be67bfb7ef2021dbe3c1f72/flexget/utils/parsers/series.py#L90

The part that captures the episode number is using `\d{1,3}` which stops at 3 digits at most, that's why it can't capture any episode with more than 3 digits.

This regex is used in different places in this file as well, but that line looks to be specific to the "sequence" type, which is the case here, but the others may need a look too.

It seems weird to me that the part that captures the season number is using `\d{1,4}` instead!  I think the episodes number would usually be larger than the seasons number.

**Comment by BrutuZ** [comment]
You could solve for these exceptions directly in the config with https://flexget.com/Plugins/series/regexps#episode-numbering-matching
```yaml
series:
  settings:
    sequence_regexp:
      - 1(\d{1,3})
```

**Comment by astrotee** [comment]
Thanks, didn't know this one; It'd make it easier for testing.

**Comment by jasonlyle88** [comment]
Just implemented the workaround from @BrutuZ (thanks for this btw! Had no idea we could do this) and ran into another issue. My matches stopped recognizing 1080p as a quality (I assume because it matched the sequence_regexp). As soon as I removed the above workaround, my execution recognized the 1080p version of another show and it went through fine. Because of this, I recommend the following improvement:

```yaml
series:
  settings:
    sequence_regexp:
      - \b(1\d{1,3})(?!p)\b
```

**Comment by BrutuZ** [comment]
Nice catch. I assumed the the boundary anchors would be added automatically in the background as it happens with some segments in code like `quality` expressions.

**Comment by stranger-danger-zamu** [comment]
No need to specify a maximum number sequence length. Using jasonlyle88's contribution:

```yaml
series:
  settings:
    sequence_regexp:
      - \b(\d{1,})(?!p)\b
```

The regex above should match sequence lengths if they are at least one digit long.

**Comment by jasonlyle88** [comment]
@stranger-danger-zamu 
Well, that just makes too much sense! 🤣 Good catch, not sure why I specified a maximum length! Thanks!

**Comment by BrutuZ** [comment]
> No need to specify a maximum number sequence length

@stranger-danger-zamu Not *needed* but safer and good practice to narrow down your RegExs to avoid false-positive matches.
Defining it that open could wrongly match titles that have numbers on it like `Jobless Reincarnation - Part 2`, `Invasion 2021` , ...

Practical Example:
```yaml
  test:
    mock:
      - title: "[Flexget] Mushoku Tensei - Jobless Reincarnation - Part 2 - 1234 [1080p]"
    series:
      - "Mushoku Tensei: Jobless Reincarnation":
          identified_by: sequence
          sequence_regexp:
            - \b(\d{1,})(?!p)\b
```
LOG:
```
2021-12-28 20:50:08 VERBOSE  details       test            Produced 1 entries.
2021-12-28 20:50:08 VERBOSE  task          test            ACCEPTED: `[Flexget] Mushoku Tensei - Jobless Reincarnation - Part 2 - 1234 [1080p]` by series plugin because choosing first acceptable match
2021-12-28 20:50:08 VERBOSE  details       test            Summary - Accepted: 1 (Rejected: 0 Undecided: 0 Failed: 0)
2021-12-28 20:50:08 WARNING  task          test            Task doesn't have any output plugins, you should add (at least) one!
-- Accepted: ---------------------------
title            : [Flexget] Mushoku Tensei - Jobless Reincarnation - Part 2 - 1234 [1080p]
url              : mock://localhost/mock/-2761314538689614571
original_url     : mock://localhost/mock/-2761314538689614571
accepted_by      : series
media_id         : mushoku tensei: jobless reincarnation s2021e00
original_title   : [Flexget] Mushoku Tensei - Jobless Reincarnation - Part 2 - 1234 [1080p]
proper           : False
proper_count     : 0
quality          : 1080p
reason           : choosing first acceptable match
release_group    : None
season_pack      : None
series_episodes  : 1
series_exact     : False
series_id        : 2
series_id_type   : sequence
series_identified_by: sequence
series_name      : Mushoku Tensei: Jobless Reincarnation
series_parser    : <SeriesParseResult(data=[Flexget] Mushoku Tensei - Jobless Reincarnation - Part 2 - 1234 [1080p],name=Mushoku Tensei: Jobless
Reincarnation,id=2,season=0,season_pack=None,episode=2,quality=1080p,proper=0,special=False,status=OK)>
series_releases  : [1]
series_season    : 2021
task             : test
```

**Comment by stranger-danger-zamu** [comment]
If we really care about safety, we should be building reg exp per series and match the entire title into subgroups instead of matching multiple, separate reg exps against a single string. 

Regardless, you could also just do something like:

```
series:
  settings:
    sequence_regexp:
      - \b([01]?\d{1,3})(?!p)\b
```

This'll match 3 or 4 digits only if the number is under 1999. Of course you could replace the leading character to a `\d`.

**Comment by jasonlyle88** [comment]
Once again commenting because this is, in fact, still an issue...
