### ISSUE TITLE
Seen forget --tasks behaviour

### ISSUE THREAD

**Issue by paranoidi** [Flexget/Flexget#3442]
### Expected behaviour:

`flexget seen forget --tasks "link-*` should remove everything from all tasks matching the glob. It does not run.

### Behaviour:

`flexget seen forget: error: the following arguments are required: <value>`

Also arg name `--tasks` does not match with exec which is not in plural.

**Comment by BrutuZ** [comment]
`--tasks` is a flag for `flexget execute`, not `seen`. You just do `flexget seen forget task-name`, it doesn't take glob patterns though

**Comment by paranoidi** [comment]
Look either `flexget seen forget -h` or code. It does have `--tasks`, it just doesn't seem to work properly.

**Comment by BrutuZ** [comment]
I did, hence the edit before 😅

**Comment by gazpachoking** [comment]
Hmm. `flexget seen forget [--help] [--tasks TASK [TASK ...]] <value>` is the help text, which means you need to specify value after the --tasks parameter. The problem is that you can't actually do that, because --tasks will consume multiple task names if specified.

I think we should change to --task, and make it only consume one value. Then you'd do `flexget seen forget --task task1 --task task2 some.title.here` to forget from multiple tasks.

It's also really confusing that `<value>` could be a task name, which is a totally separate thing than `--tasks`, and `<value>` doesn't take wildcards when it's a task name.

**Comment by gazpachoking** [comment]
@paranoidi How do those changes look?
