### ISSUE TITLE
Statement is returning 'NoneType' object has no attribute 'tzinfo'

### ISSUE THREAD

**Issue by xInsertx** [Flexget/Flexget#4000]
I've been running the same config for a few years now (moved from BSD to docker last year) and it seems recent docker update might  have broken something time related. Not sure if this is app or container related - so figure id asks here first.

The statement I am using is:
```
if:
- transmission_progress == 100: accept
- transmission_date_done > now - timedelta(minutes=30): reject
```

### Expected behavior:
The eval should return accept once 30mins has past.

### Actual behavior:
The task never runs properly and logs the error.

I have confirmed using --dump that the transmission_date_done field is fine - so leaning towards 'now' maybe being the issue?

#### Log:
<details>
 <summary>(click to expand)</summary>

```
Error occurred while evaluating statement `transmission_date_done > now - timedelta(minutes=30)`. ('NoneType' object has no attribute 'tzinfo')
```
</details>

### Additional information:

- FlexGet version: 3.11.35 (inside container)
- Python version: 3.11.9 (inside container)
- Installation method: Docker Compose (linuxserver_io - latest)
- Docker Image BuildInfo: "Linuxserver.io version:- v3.11.35-ls99 Build-date:- 2024-05-28T15:53:06+00:00"
- TZ env is set (and confirmed correct via exec date in the container)
- FG_LOG_LEVEL + FILE and CONFIG env are set

**Comment by gazpachoking** [comment]
There were some changes with times, but it shouldn't break your case. I did find a couple issues that I fixed for the next release though:
- The message about has no tzinfo was a bit confusing, and obscures the appropriate error, which should be something like ```Error occurred while evaluating statement `transmission_date_done > now.subtract(minutes=30)`. ('>' not supported between instances of 'NoneType' and 'CoercingDateTime')```
- transmission_date_done was always in UTC, which was incorrect, and would break the math. It's now set in the appropriate time zone.

It really looks like the issue you are running in to is when transmission_date_done is None. I'm guessing the bug I just fixed with the wrong time zone was messing up your logic, and that error was from a different torrent that actually wasn't finished.

**Comment by xInsertx** [comment]
Makes sense - happy to test when its pushed to next release or if you can point me to a test build docker image.

**Comment by gazpachoking** [comment]
New version is out, you can give it a go now.

**Comment by xInsertx** [comment]
For testing I add 5 torrents of similar size and the task does seem to process now. I did notice 3 logs matching what you mentioned above but the task did process on the next run.

I'm wondering if its similar to another issue a while back were tr_progress could be 100% but tr_date_done can be delayed getting set? Maybe as it transitions to seeding or the file moving?

Either way the cleanup tasks appear to be running again now. So unless you would like to me to debug anything else happy to close it.
