### ISSUE TITLE
flexget and thexem - hammering/no id/etc

### ISSUE THREAD

**Issue by thezoggy** [Flexget/Flexget#839]
this morning I woke up to thexem getting hammered and while digging through logs researching on who/what was the reasons I noticed that flexget users send a lot of duplicate url requests and invalid ones at that too.

some examples:

a FlexGet/1.2.441 user sent over 7,300 requests in an hour, with hundreds of the same request url for each show:
![spunk49](http://zoggy.net/splunk49.png)

a FlexGet/1.2.442 user sent 1,524 calls in 5 mins.. 500 of them the same url show: 
![splunk50](http://zoggy.net/splunk50.png)

a FlexGet/1.2.441 user sent 11,211 requests in 1 hr.. 3,612 of those requests was to same id: ![splunk52](http://zoggy.net/splunk52.png)

a FlexGet/1.2.412 user has sent over 7,000 requests today, and 656 of them were for the show id `None` -- which is never going to yield anything.
![splunk53](http://zoggy.net/splunk53.png)

looking back at the last 7 days,  14,818 api requests submitted by flexget users for `/map/all?id=None&origin=tvdb` which shows that this is more than a single user issue.

**Comment by crawln45** [comment]
Well to be honest that is a user plugin that was shared with the community. Since we don't actually support this plugin and it's not shipped with our package. Not something we can do anything about. The searching for none is probably just bad coding. The thousands of duplicate lookups is that not uncommon in a large user base. To be honest I didn't even realize there were that many users using that plugin or even that that plugin existed.

**Comment by liiight** [comment]
@crawln45 I'm not familiar with that plugin, can you enlighten me? Maybe we could make it official and fix it.

**Comment by thezoggy** [comment]
@crawln45 there is not many flexget users hitting xem.. just the ones that are, send thousands of requests for the same info over and over.. or bad requests. The worst part is that they send their requests back to back over and over.. basically dossing the server for the same info. Even though I have a cache layer, thats still wasted cpu cycles. 

Regardless, I would suspect it is just due to bad coding/wokflow which I would hope could get address. I do not use flexget so I don't know if it has any caching ability or if the plugin system is unaware of series structure/understands how to use xem.. if there is nothing that can be done on your end I will just have to look at ways to block/throttle on my side.

Just food for thought, I see over 30,000 api requests from just 4 flexget users while another app to hit 30k api requests it takes several thousands of their users.

**Comment by crawln45** [comment]
@thezoggy Interesting. Didn't realize it was just a few users. We actually build our plugins with caching in mind by adding tables to the sqlite database so we don't hammer api's for requests. I'm not exactly sure what this plugin does to begin with or what the api of yours returns that they want. Seems like the original plugin was from https://github.com/z00nx/flexget-plugins/blob/master/thexem.py.  
Based on what I'm reading looks like this is very poorly designed and implemented. Might also comment on that account as well. Letting them know that they should either update the plugin to support caching or throttling them. No plugin should make thousands of calls for the same data ever.

**Comment by liiight** [comment]
@thezoggy I think we will make that plugin official and bundle it with Flexget so we can control it and fix it. like @crawln45 said, flexget is definietly built around caching and using as less traffic as possibly can in mind.

That being said, that could take a while and it obviously won't stop any other 3rd party plugin or even completely different app that will reproduce this issue. So I would look into handling this issue on your end as well.

**Comment by liiight** [comment]
This plugin will be removed from our wiki untill fixed.

**Comment by jawilson** [comment]
As noted in the plugin source, I just took it from https://github.com/z00nx/flexget-plugins. I've been meaning to fix it up, but haven't gotten around to it. I mentioned in https://github.com/jawilson/dotfiles/issues/5 caching can easily triage the issue. Bringing it within the official Flexget project would be great!

**Comment by liiight** [comment]
well, fix it up and issue a PR :smile:

**Comment by thezoggy** [comment]
Looking back on the Jan 29th, I see that all the api requests coming from flexget was about 76k requests, which is nothing..  but I see that there was only 13 distinct ips. For right now I've blocked the 5 top offenders that make up almost half those requests for right now.

for transparency's sake, I blocked these flexget ips yesterday:
```
sudo iptables -A INPUT -s 207.144.11.78 -j DROP
sudo iptables -A INPUT -s 172.98.67.72 -j DROP
sudo iptables -A INPUT -s 184.58.167.31 -j DROP
sudo iptables -A INPUT -s 63.131.206.175 -j DROP
sudo iptables -A INPUT -s 50.174.189.55 -j DROP
```

 I will be more than happy to unblock them once xem plugin gets into the fold.. 

In the last 24 hours xem served up 1,808,660 api requests (1/30/16 10:00:00.000 AM to 1/31/16 10:27:57.000 AM) - this is post blocking of ips.

**Comment by jbaddock** [comment]
thezoggy....  My apologies for being part of that problem, as I am in that list you just submitted.  I just brought online a task over the last few days, and I believe that is part of the problem.  It was not doing that before.
I've disable this task until I can look into this further and not be a part of the problem.

**Comment by stevezau** [comment]
@jbaddock can you confirm that task is uing the plugin mentioned above? https://github.com/z00nx/flexget-plugins/blob/master/thexem.py

**Comment by jbaddock** [comment]
stevezau.  Yes I can confirm that.  I have been following Jeff's and Giorgio's script as a guildeline, I am sure I did something incorrect.  I just commented out thexem and reloaded my script, and saved my logfiles aside for now.  I know that thezoggy is dropping the packets, but regardless it should stop the requests.

**Comment by thezoggy** [comment]
@jbaddock if you provide your ip address I will be happy to unblock it

**Comment by jbaddock** [comment]
@thezoggy I was second on the list, but I changed my IP after I disabled thexem requests.  
I think I know why the request "show id None" was being sent to your server too.  Will be looking into this to confirm.  Will post back.

**Comment by sisfs** [comment]
I was one of the offending ips as well... I have commented out the lines
calling thexem in my config and reloaded as well.

To be honest, I'm not sure what thexem plugin was supposed to provide...
@jawilson had the calls in the config I forked. I have commented them out a
couple of times before and had recently put them back in when I rolled back
to an old config attempting to fix another problem. Does anyone have an
idea of what my, and the other's, configs could be doing to cause the
issue? Do I need thexem in place for a specific reason, and if so, what is
that reason?

**Comment by jbaddock** [comment]
@sisfs 
**The Xross Entity Map for TV shows**   http://thexem.de/
_xem helps you keep an overview of your shows on different websites.
Many websites use different numberings, names and season titles for the same show.
xem lets you create a map for an easy overview of all the different counting and naming system_

It looks like a great future addition to flexget, creates a master from multiple sources that has different numbering.

I had just enabled the "backfill/find missing" task (similar to Jeff's, as that is where I originally started too), but I added a second plugin.  I also mistakenly scheduled this for every 2 hours, a copy and paste mistake.  Should have been days....and 5 days is fine with me.  All these requests were being sent to XEM, every time the task ran.

From what was said above, it sounds like the official plugins cache to the db-config.sqlite when used properly, but XEM is not an official plugin (yet), so no caching was done.  So every task that calls XEM would send every request every time it was called, as there is no caching configured on the user side into the local database.  In my instance I believe it was 2 search plugins, coupled by 12 times a day for the task.  And I most likely had an improper config, since there was "1,524 calls in 5 mins.. 500 of them the same url show".  Unless that was what the plugin was sending....

Looking forward to understanding/learning what happened

**Comment by sarethan** [comment]
I too was one of the offending IP's and have commented out theexem and reloaded. I also was following @jawilson 's config.

**Comment by paranoidi** [comment]
3rd party issue

**Comment by thezoggy** [comment]
68k requests by 1 flexget user 184.58.167.31 in two hours :(
![splunk55c](http://zoggy.net/splunk55c.png)

**Comment by blsmit5728** [comment]
Just wanted to throw my hat in this ring, I use thexem plugin as well for Flexget (thexem is amazing by the way) My IP doesn't appear in your list, and I'm going to guess I hit it about as often as @jawilson does. Keeping an eye on this and will move to the cached version once integrated into Flexget.
