### ISSUE TITLE
Trakt metadata changes confuses configure_series

### ISSUE THREAD

**Issue by leetwanker** [Flexget/Flexget#840]
I've been using configure_series + trakt for a while now to set up my filters. 

Lately I've started to get duplicates due to trakt changing the year of the show. I think at one point I had the option of the year not being included in my following list, but I thought it would help with matching if I left it enabled. 

So now, any time trakt changes the year of a show, which they seem to do way more often than you'd think, it leaves the old show behind in the db and starts grabbing all the episodes it sees. 

Is there some way for me to edit the flexget db to rename all my series w/o the (yyyy) at the end so I can prevent this from happening without starting fresh?

**Comment by liiight** [comment]
1. You can do it via CLI with series command. 
2. You can use the new series API too.

**Comment by leetwanker** [comment]
I think trakt changing a year and thus messing up your database should be considered an issue.

**Comment by liiight** [comment]
we're not and can't be responsible for the input of an input plugin. The plugin works correctly, and even has a `strip_dates` option built in to it. There's no code to fix.

I agree with you that it just sucks, but that doesn't mean it's a flexget issue.
Of course that just my opinion and if someone thinks otherwise it's perfectly valid. We can always do a DB fix that will try to merge those changes but i'm very wary of those types of operations.

**Comment by leetwanker** [comment]
I don't know how to look at the trakt list in the raw format like i assume flexget is fetching, but I wonder if there's some sort of series id like tvdb uses that could be checked to see if that show is already in the database under a different name. Just something static that isn't changeable and is specific to each show so a metadata change on their part can't just spin off a whole new series to start fetching in the series database. 

Maybe it's not possible, just an idea. I'm now stripping all the dates to prevent any more of this happening.
